version: "3.3"
services:

  db:
    image: "postgres:latest"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env_file

  streamlit:
    build:
      context: .
    container_name: "streamlit"
    ports:
      - "8501:8501"

volumes:
  db_data:
